/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/api/v1/org/{org}": {
    /** get one org by ID */
    get: operations["get_api-v1-org-e5659494460fbdef2fe5e110ad7644e8"];
    /** update org */
    put: operations["put_api-v1-org-e5659494460fbdef2fe5e110ad7644e8"];
  };
  "/api/v1/org/{org}/auth": {
    /** login for org */
    post: operations["post_api-v1-org-4e7473169fa823300fa931e3c864e9a6"];
  };
  "/api/v1/orgs/self_register": {
    /** self-register a new org */
    post: operations["post_api-v1-orgs-self_register-0556be35dff40f12eac6263dd7d00514"];
  };
  "/api/v1/org/{org}/events": {
    /** get event list for a org */
    get: operations["get_api-v1-org-7dc929bdfbe96d14e91c23f78cd42f84"];
  };
  "/api/v1/org/{org}/{event}/teams": {
    /** get team list for an org + event */
    get: operations["get_api-v1-org-640c441034f7cd1e205777f7f2c464b4"];
  };
  "/api/v1/org/{org}/{event}/questionnaire_answer": {
    /** get questionaire answers for org + event */
    get: operations["get_api-v1-org-d4383d01e537aadc8f5d0a2bde36494a"];
  };
  "/api/v1/org/{org}/{event}/invite": {
    /** invite an org to an event */
    post: operations["post_api-v1-org-9d1624e23d71d9d47a3ddda43d4a0ee0"];
  };
  "/api/v1/invites": {
    /** get invites */
    get: operations["get_api-v1-invites-4a7e45dfc0832f05a15444003398849c"];
    /** send a single invite */
    post: operations["post_api-v1-invites-4a7e45dfc0832f05a15444003398849c"];
  };
  "/api/v1/org/{org}/{event}": {
    /** get event status for an org */
    get: operations["get_api-v1-org-4edb397f1ce33a3e430233fb4a2e8e52"];
  };
  "/api/v1/org/{org}/{event}/questionnaire": {
    /** get questionaire for org + event */
    get: operations["get_api-v1-org-4d5c5cb89714f7f4d5fd83d07ae2dd18"];
  };
  "/api/v1/orgs": {
    /** get list of orgs */
    get: operations["get_api-v1-orgs-4bb4bb74212e29d1e33641b38d211873"];
  };
  "/api/v1/org": {
    /** add an org */
    post: operations["post_api-v1-org-4d6e7ea32cc332b1579e5eb57812ec6c"];
  };
  "/api/v1/event/{event}": {
    /** get one event by ID */
    get: operations["get_api-v1-event-616b52a3214d1d1a472d3a61bef77f20"];
    /** update event */
    put: operations["put_api-v1-event-616b52a3214d1d1a472d3a61bef77f20"];
  };
  "/api/v1/event/{event}/questionnaire_answers": {
    /** get questionaire answers for all orgs in event */
    get: operations["get_api-v1-event-09be1ab5aad59adce5febf4bf74460a6"];
  };
  "/api/v1/event/{event}/pairings/{group}/{round}": {
    /** set pairings for a given event + group */
    put: operations["put_api-v1-event-22f93462af22d1552b7828cb1461a501"];
  };
  "/api/v1/event/{event}/sse": {
    /** read SSE */
    get: operations["get_api-v1-event-c75ee2cb262d7198504f47ae0a83472a"];
  };
  "/api/v1/event/{event}/results/{group}/{round}": {
    /** set results for a given event + group */
    put: operations["put_api-v1-event-27c0f944dfda8590fa5b4ebeb75c8132"];
  };
  "/api/v1/event/{event}/timetable": {
    /** get timetable for a given event */
    get: operations["get_api-v1-event-0f47f13f2647148a3535420643899eff"];
    /** set timetable for a given event + group */
    put: operations["put_api-v1-event-0f47f13f2647148a3535420643899eff"];
  };
  "/api/v1/event/{event}/rooms/{group}": {
    /** set rooms for a given event + group */
    put: operations["put_api-v1-event-32fa1b098b899b8b7012a6eeb84bb174"];
  };
  "/api/v1/event/{event}/rooms": {
    /** get rooms for a given event */
    get: operations["get_api-v1-event-ef99e312f73e4b677af08a0e6c2069e8"];
  };
  "/api/v1/event/{event}/pairings": {
    /** get pairings for a given event + group */
    get: operations["get_api-v1-event-e5839bcc54123a8e476f3e95fd56d323"];
  };
  "/api/v1/event/{event}/results": {
    /** get results for a given event + group */
    get: operations["get_api-v1-event-3129d62da168c0e0b04d9e202779e572"];
  };
  "/api/v1/event/{event}/questionnaire": {
    /** get questionaire for event */
    get: operations["get_api-v1-event-216083259df8aeef507bc5fa2036a212"];
    /** create questionaire for event */
    post: operations["post_api-v1-event-216083259df8aeef507bc5fa2036a212"];
  };
  "/api/v1/event/{event}/groups": {
    /** get list of groups */
    get: operations["get_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5"];
    /** add a group */
    post: operations["post_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5"];
  };
  "/api/v1/group": {
    /** update group */
    put: operations["put_api-v1-group-44e4a130606b544f6ab5a1532e35bc29"];
  };
  "/api/v1/group/{group}": {
    /** get group by id */
    get: operations["get_api-v1-group-0b9bee095d760068add3c5fe8a467e8b"];
    /** delete a group */
    delete: operations["delete_api-v1-group-0b9bee095d760068add3c5fe8a467e8b"];
  };
  "/api/v1/group/{group}/changed_since_export": {
    /** clear changed_since_export for group */
    delete: operations["delete_api-v1-group-d8212f5147a935d21f14aa23761218c8"];
  };
  "/api/v1/event/{event}/orgs": {
    /** get org list for a given event */
    get: operations["get_api-v1-event-45c1132012c55c1196f21c335b92f888"];
  };
  "/api/v1/team": {
    /** update team */
    put: operations["put_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb"];
    /** create a new team */
    post: operations["post_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb"];
  };
  "/api/v1/team/presence_state": {
    /** update team presence state */
    put: operations["put_api-v1-team-presence_state-d8d4cd4c9d792cccbc08087e3e2e9346"];
  };
  "/api/v1/team/{team}": {
    /** get one team by ID */
    get: operations["get_api-v1-team-660a5317bb41a757a76ba890440c3a2e"];
    /** delete a team */
    delete: operations["delete_api-v1-team-660a5317bb41a757a76ba890440c3a2e"];
  };
  "/api/v1/event/{event}/org/{org}": {
    /** set status for event per org */
    put: operations["put_api-v1-event-de93f4166d70a3ac4838a8865d319cc1"];
  };
  "/api/v1/events": {
    /** get list of events */
    get: operations["get_api-v1-events-bc4c42038b2c2f0b5c7deb650fb28842"];
  };
  "/api/v1/event": {
    /** add an event */
    post: operations["post_api-v1-event-28122581fdbc5bd19bb7de68ab3a43f6"];
  };
  "/api/v1/auth": {
    /** get logged in identity */
    get: operations["get_api-v1-auth-0a4ec84191b3223053d50fc370e78726"];
    /** login */
    post: operations["post_api-v1-auth-0a4ec84191b3223053d50fc370e78726"];
    /** logout */
    delete: operations["delete_api-v1-auth-0a4ec84191b3223053d50fc370e78726"];
  };
  "/api/v1/questionnaire/{id}": {
    /** delete questionaire */
    delete: operations["delete_api-v1-questionnaire-b5de40df4a370ee055cf689cfafdc2d4"];
  };
  "/api/v1/questionnaire": {
    /** update questionaire */
    put: operations["put_api-v1-questionnaire-4553825757f17c4aa7cc1166ac08b07c"];
  };
  "/api/v1/questionnaire_answer": {
    /** update questionaire answer */
    put: operations["put_api-v1-questionnaire_answer-577a63f9ae75b3eb44ae024d56cfea36"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AuthData */
    AuthData: {
      email: string;
      password: string;
    };
    /**
     * Event
     * @description Event details
     */
    Event: {
      allow_set_present: boolean;
      allow_user_changes: boolean;
      /** Format: partial-date-time */
      begin?: string | null;
      description: string;
      id: string;
      name: string;
      public: boolean;
      /** Format: partial-date-time */
      public_reg_until?: string | null;
      registration_active: boolean;
      /** Format: partial-date-time */
      registration_start_date?: string | null;
      results_are_public: boolean;
      self_registration_allowed: boolean;
    };
    /** EventOrg */
    EventOrg: {
      /** @description Org details */
      org: components["schemas"]["Org"];
      /** @description org state for this event */
      state: components["schemas"]["EventOrgState"];
      /** @description teams for this event */
      teams: components["schemas"]["Team"][];
    };
    EventOrgState: "NotEnlisted" | "Registered" | "Invited" | "Updated" | "Submitted" | "Verified";
    /** EventOrgStateUpdate */
    EventOrgStateUpdate: {
      state: components["schemas"]["EventOrgState"];
    };
    EventQuestionnaireAnswer: {
      answers: components["schemas"]["QuestionnaireAnswer"][];
      event_org_state: components["schemas"]["EventOrgState"];
      org: components["schemas"]["Org"];
    };
    /** EventQuestionnaireAnswers */
    EventQuestionnaireAnswers: {
      orgs: components["schemas"]["EventQuestionnaireAnswer"][];
      questions: components["schemas"]["Questionnaire"][];
    };
    /**
     * Group
     * @description Group details
     */
    Group: {
      color: string;
      event_id: string;
      id: string;
      name: string;
      /** Format: int32 */
      num_rounds: number;
      replacement?: string | null;
      slug: string;
    };
    /** Invite */
    Invite: {
      event: components["schemas"]["Event"];
      org: components["schemas"]["Org"];
      secret: string;
    };
    /** MailConfirm */
    MailConfirm: {
      send: boolean;
    };
    /**
     * NewEvent
     * @description New event details.
     */
    NewEvent: {
      name: string;
    };
    /** NewGroup */
    NewGroup: {
      name: string;
    };
    /**
     * NewOrg
     * @description New org details.
     */
    NewOrg: {
      name: string;
    };
    /** NewOrgSelfReg */
    NewOrgSelfReg: {
      contact_email: string;
      contact_name: string;
      /** Format: uuid */
      event_id: string;
      name: string;
    };
    /**
     * NewTeam
     * @description New org details.
     */
    NewTeam: {
      event: string;
      name: string;
      org: string;
    };
    /** @description Org details. */
    Org: {
      contact_email?: string | null;
      contact_email_pending?: string | null;
      contact_name?: string | null;
      contact_phone?: string | null;
      genus?: string | null;
      id: string;
      /** Format: partial-date-time */
      last_update: string;
      name: string;
      name_additional?: string | null;
      public: boolean;
      slug: string;
    };
    /** OrgAuthLoginData */
    OrgAuthLoginData: {
      token: string;
    };
    /** OrgEvent */
    OrgEvent: {
      /** @description Event details */
      event: components["schemas"]["Event"];
      /** @description org state for this event */
      state: components["schemas"]["EventOrgState"];
      /** @description teams for this event */
      teams: components["schemas"]["Team"][];
    };
    Pairing: {
      event: string;
      group_id: string;
      /** Format: int32 */
      points_guest?: number | null;
      /** Format: int32 */
      points_home?: number | null;
      result?: string | null;
      /** Format: int32 */
      round: number;
      /** Format: int32 */
      table_num: number;
      team_guest?: string | null;
      team_home?: string | null;
    };
    PairingEntry: {
      group: string;
      /** Format: int32 */
      points_guest?: number | null;
      /** Format: int32 */
      points_home?: number | null;
      /** Format: int32 */
      round: number;
      /** Format: int32 */
      table: number;
      team_guest?: string | null;
      team_guest_org?: string | null;
      team_home?: string | null;
      team_home_org?: string | null;
    };
    /** PairingForEvent */
    PairingForEvent: {
      event_name: string;
      groups: components["schemas"]["Group"][];
      pairings: components["schemas"]["PairingEntry"][];
      rooms: components["schemas"]["Room"][];
    };
    /** Questionnaire */
    Questionnaire: {
      event_id?: string | null;
      id: string;
      org_id?: string | null;
      question_data: string;
      question_text: string;
      question_type: string;
      /** Format: int32 */
      sort: number;
    };
    /** QuestionnaireAnswer */
    QuestionnaireAnswer: {
      event_id: string;
      org_id: string;
      question_answer: string;
      question_id: string;
    };
    ResultEntry: {
      group: string;
      /** Format: int32 */
      points_player?: number | null;
      /** Format: int32 */
      points_team?: number | null;
      /** Format: int32 */
      rank?: number | null;
      /** Format: int32 */
      round: number;
      team?: string | null;
      team_genus?: string | null;
      team_org?: string | null;
      /** Format: int32 */
      tie?: number | null;
    };
    /** ResultsForEvent */
    ResultsForEvent: {
      event_name: string;
      groups: components["schemas"]["Group"][];
      results: components["schemas"]["ResultEntry"][];
    };
    Role: OneOf<["None" | "Admin", {
      /** Format: uuid */
      Org: string;
    }]>;
    Room: {
      event: string;
      group_id: string;
      room: string;
      /** Format: int32 */
      table_num_high: number;
      /** Format: int32 */
      table_num_low: number;
    };
    /** SetPairingPayload */
    SetPairingPayload: {
      pairings: components["schemas"]["Pairing"][];
    };
    /** SetResultsPayload */
    SetResultsPayload: {
      results: components["schemas"]["TeamResult"][];
    };
    /** SetRoomsPayload */
    SetRoomsPayload: {
      rooms: components["schemas"]["Room"][];
    };
    /** SetTimetablePayload */
    SetTimetablePayload: {
      timetable: components["schemas"]["TimetableEntry"][];
    };
    /** SlimUser */
    SlimUser: {
      email: string;
      role: components["schemas"]["Role"];
    };
    /**
     * Team
     * @description Team details.
     */
    Team: {
      changed_since?: string | null;
      changed_since_export: boolean;
      comment?: string | null;
      contact_name?: string | null;
      contact_phone?: string | null;
      event: string;
      group_id?: string | null;
      id: string;
      name: string;
      org: string;
      presence_state: string;
    };
    /** TeamReady */
    TeamReady: {
      presence_state: string;
      /** Format: uuid */
      team_id: string;
    };
    TeamResult: {
      event: string;
      group_id: string;
      /** Format: int32 */
      points_player?: number | null;
      /** Format: int32 */
      points_team?: number | null;
      /** Format: int32 */
      rank?: number | null;
      /** Format: int32 */
      round: number;
      team?: string | null;
      /** Format: int32 */
      tie?: number | null;
    };
    TimetableEntry: {
      event: string;
      /** Format: partial-date-time */
      expected_time: string;
      flags: string;
      group_id: string;
      /** Format: partial-date-time */
      last_update: string;
      name: string;
      /** Format: int32 */
      row_index: number;
      state: string;
    };
    /** TimetableForEvent */
    TimetableForEvent: {
      event_name: string;
      groups: components["schemas"]["Group"][];
      rows: components["schemas"]["TimetableRow"][];
    };
    TimetableRow: {
      /** Format: partial-date-time */
      expected_time: string;
      flags: string;
      group: string;
      /** Format: partial-date-time */
      last_update: string;
      name: string;
      /** Format: int32 */
      row_index: number;
      state: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** get one org by ID */
  "get_api-v1-org-e5659494460fbdef2fe5e110ad7644e8": {
    parameters: {
      path: {
        org: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update org */
  "put_api-v1-org-e5659494460fbdef2fe5e110ad7644e8": {
    parameters: {
      path: {
        org: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Org"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** login for org */
  "post_api-v1-org-4e7473169fa823300fa931e3c864e9a6": {
    parameters: {
      path: {
        org: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrgAuthLoginData"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** self-register a new org */
  "post_api-v1-orgs-self_register-0556be35dff40f12eac6263dd7d00514": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewOrgSelfReg"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get event list for a org */
  "get_api-v1-org-7dc929bdfbe96d14e91c23f78cd42f84": {
    parameters: {
      path: {
        org: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrgEvent"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get team list for an org + event */
  "get_api-v1-org-640c441034f7cd1e205777f7f2c464b4": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Team"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get questionaire answers for org + event */
  "get_api-v1-org-d4383d01e537aadc8f5d0a2bde36494a": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnaireAnswer"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** invite an org to an event */
  "post_api-v1-org-9d1624e23d71d9d47a3ddda43d4a0ee0": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get invites */
  "get_api-v1-invites-4a7e45dfc0832f05a15444003398849c": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Invite"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** send a single invite */
  "post_api-v1-invites-4a7e45dfc0832f05a15444003398849c": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MailConfirm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get event status for an org */
  "get_api-v1-org-4edb397f1ce33a3e430233fb4a2e8e52": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EventOrgState"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get questionaire for org + event */
  "get_api-v1-org-4d5c5cb89714f7f4d5fd83d07ae2dd18": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Questionnaire"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of orgs */
  "get_api-v1-orgs-4bb4bb74212e29d1e33641b38d211873": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add an org */
  "post_api-v1-org-4d6e7ea32cc332b1579e5eb57812ec6c": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewOrg"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get one event by ID */
  "get_api-v1-event-616b52a3214d1d1a472d3a61bef77f20": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update event */
  "put_api-v1-event-616b52a3214d1d1a472d3a61bef77f20": {
    parameters: {
      path: {
        event: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Event"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get questionaire answers for all orgs in event */
  "get_api-v1-event-09be1ab5aad59adce5febf4bf74460a6": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EventQuestionnaireAnswers"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** set pairings for a given event + group */
  "put_api-v1-event-22f93462af22d1552b7828cb1461a501": {
    parameters: {
      path: {
        event: string;
        group: string;
        round: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPairingPayload"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** read SSE */
  "get_api-v1-event-c75ee2cb262d7198504f47ae0a83472a": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
    };
  };
  /** set results for a given event + group */
  "put_api-v1-event-27c0f944dfda8590fa5b4ebeb75c8132": {
    parameters: {
      path: {
        event: string;
        group: string;
        round: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetResultsPayload"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get timetable for a given event */
  "get_api-v1-event-0f47f13f2647148a3535420643899eff": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TimetableForEvent"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** set timetable for a given event + group */
  "put_api-v1-event-0f47f13f2647148a3535420643899eff": {
    parameters: {
      path: {
        event: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetTimetablePayload"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** set rooms for a given event + group */
  "put_api-v1-event-32fa1b098b899b8b7012a6eeb84bb174": {
    parameters: {
      path: {
        event: string;
        group: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetRoomsPayload"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get rooms for a given event */
  "get_api-v1-event-ef99e312f73e4b677af08a0e6c2069e8": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Room"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get pairings for a given event + group */
  "get_api-v1-event-e5839bcc54123a8e476f3e95fd56d323": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PairingForEvent"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get results for a given event + group */
  "get_api-v1-event-3129d62da168c0e0b04d9e202779e572": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ResultsForEvent"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get questionaire for event */
  "get_api-v1-event-216083259df8aeef507bc5fa2036a212": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Questionnaire"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** create questionaire for event */
  "post_api-v1-event-216083259df8aeef507bc5fa2036a212": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Questionnaire"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of groups */
  "get_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add a group */
  "post_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5": {
    parameters: {
      path: {
        event: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewGroup"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update group */
  "put_api-v1-group-44e4a130606b544f6ab5a1532e35bc29": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get group by id */
  "get_api-v1-group-0b9bee095d760068add3c5fe8a467e8b": {
    parameters: {
      path: {
        group: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** delete a group */
  "delete_api-v1-group-0b9bee095d760068add3c5fe8a467e8b": {
    parameters: {
      path: {
        group: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** clear changed_since_export for group */
  "delete_api-v1-group-d8212f5147a935d21f14aa23761218c8": {
    parameters: {
      path: {
        group: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get org list for a given event */
  "get_api-v1-event-45c1132012c55c1196f21c335b92f888": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EventOrg"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update team */
  "put_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Team"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** create a new team */
  "post_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewTeam"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Team"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update team presence state */
  "put_api-v1-team-presence_state-d8d4cd4c9d792cccbc08087e3e2e9346": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamReady"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get one team by ID */
  "get_api-v1-team-660a5317bb41a757a76ba890440c3a2e": {
    parameters: {
      path: {
        team: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Team"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** delete a team */
  "delete_api-v1-team-660a5317bb41a757a76ba890440c3a2e": {
    parameters: {
      path: {
        team: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** set status for event per org */
  "put_api-v1-event-de93f4166d70a3ac4838a8865d319cc1": {
    parameters: {
      path: {
        event: string;
        org: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventOrgStateUpdate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of events */
  "get_api-v1-events-bc4c42038b2c2f0b5c7deb650fb28842": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add an event */
  "post_api-v1-event-28122581fdbc5bd19bb7de68ab3a43f6": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewEvent"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get logged in identity */
  "get_api-v1-auth-0a4ec84191b3223053d50fc370e78726": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SlimUser"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** login */
  "post_api-v1-auth-0a4ec84191b3223053d50fc370e78726": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthData"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** logout */
  "delete_api-v1-auth-0a4ec84191b3223053d50fc370e78726": {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** delete questionaire */
  "delete_api-v1-questionnaire-b5de40df4a370ee055cf689cfafdc2d4": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update questionaire */
  "put_api-v1-questionnaire-4553825757f17c4aa7cc1166ac08b07c": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Questionnaire"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update questionaire answer */
  "put_api-v1-questionnaire_answer-577a63f9ae75b3eb44ae024d56cfea36": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionnaireAnswer"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
}
