/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/org/{org}": {
    /** get one org by ID */
    get: operations["get_api-v1-org-e5659494460fbdef2fe5e110ad7644e8"];
    /** update org */
    put: operations["put_api-v1-org-e5659494460fbdef2fe5e110ad7644e8"];
  };
  "/api/v1/org/{org}/events": {
    /** get event list for a org */
    get: operations["get_api-v1-org-7dc929bdfbe96d14e91c23f78cd42f84"];
  };
  "/api/v1/org/{org}/{event}/teams": {
    /** get team list for an org + event */
    get: operations["get_api-v1-org-640c441034f7cd1e205777f7f2c464b4"];
  };
  "/api/v1/orgs": {
    /** get list of orgs */
    get: operations["get_api-v1-orgs-4bb4bb74212e29d1e33641b38d211873"];
  };
  "/api/v1/org": {
    /** add an org */
    post: operations["post_api-v1-org-4d6e7ea32cc332b1579e5eb57812ec6c"];
  };
  "/api/v1/event/{event}": {
    /** get one event by ID */
    get: operations["get_api-v1-event-616b52a3214d1d1a472d3a61bef77f20"];
    /** update event */
    put: operations["put_api-v1-event-616b52a3214d1d1a472d3a61bef77f20"];
  };
  "/api/v1/event/{event}/groups": {
    /** get list of groups */
    get: operations["get_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5"];
    /** add a group */
    post: operations["post_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5"];
  };
  "/api/v1/group": {
    /** update group */
    put: operations["put_api-v1-group-44e4a130606b544f6ab5a1532e35bc29"];
  };
  "/api/v1/group/{group}": {
    /** delete a group */
    delete: operations["delete_api-v1-group-0b9bee095d760068add3c5fe8a467e8b"];
  };
  "/api/v1/event/{event}/orgs": {
    /** get org list for a given event */
    get: operations["get_api-v1-event-45c1132012c55c1196f21c335b92f888"];
  };
  "/api/v1/team": {
    /** update team */
    put: operations["put_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb"];
    /** create a new team */
    post: operations["post_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb"];
  };
  "/api/v1/event/{event}/org/{org}": {
    /** set status for event per org */
    put: operations["put_api-v1-event-de93f4166d70a3ac4838a8865d319cc1"];
  };
  "/api/v1/events": {
    /** get list of events */
    get: operations["get_api-v1-events-bc4c42038b2c2f0b5c7deb650fb28842"];
  };
  "/api/v1/event": {
    /** add an event */
    post: operations["post_api-v1-event-28122581fdbc5bd19bb7de68ab3a43f6"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Event
     * @description Event details
     */
    Event: {
      /** Format: date */
      begin?: string | null;
      id: string;
      name: string;
      public: boolean;
    };
    /** EventOrg */
    EventOrg: {
      /** @description Org details */
      org: components["schemas"]["Org"];
      /** @description org state for this event */
      state: components["schemas"]["EventOrgState"];
      /** @description teams for this event */
      teams: components["schemas"]["Team"][];
    };
    /** @enum {string} */
    EventOrgState: "NotEnlisted" | "Created" | "Updated" | "Submitted";
    /** EventOrgStateUpdate */
    EventOrgStateUpdate: {
      state: components["schemas"]["EventOrgState"];
    };
    /**
     * Group
     * @description Group details
     */
    Group: {
      event_id: string;
      id: string;
      name: string;
    };
    /**
     * NewEvent
     * @description New event details.
     */
    NewEvent: {
      name: string;
    };
    /** NewGroup */
    NewGroup: {
      name: string;
    };
    /**
     * NewOrg
     * @description New org details.
     */
    NewOrg: {
      name: string;
    };
    /**
     * NewTeam
     * @description New org details.
     */
    NewTeam: {
      event: string;
      name: string;
      org: string;
    };
    /** @description Org details. */
    Org: {
      contact_email?: string | null;
      contact_phone?: string | null;
      id: string;
      name: string;
      public: boolean;
    };
    /** OrgEvent */
    OrgEvent: {
      /** @description Event details */
      event: components["schemas"]["Event"];
      /** @description org state for this event */
      state: components["schemas"]["EventOrgState"];
      /** @description teams for this event */
      teams: components["schemas"]["Team"][];
    };
    /**
     * Team
     * @description Team details.
     */
    Team: {
      contact_name?: string | null;
      contact_phone?: string | null;
      event: string;
      group_id?: string | null;
      id: string;
      name: string;
      org: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** get one org by ID */
  "get_api-v1-org-e5659494460fbdef2fe5e110ad7644e8": {
    parameters: {
      path: {
        org: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update org */
  "put_api-v1-org-e5659494460fbdef2fe5e110ad7644e8": {
    parameters: {
      path: {
        org: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Org"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get event list for a org */
  "get_api-v1-org-7dc929bdfbe96d14e91c23f78cd42f84": {
    parameters: {
      path: {
        org: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrgEvent"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get team list for an org + event */
  "get_api-v1-org-640c441034f7cd1e205777f7f2c464b4": {
    parameters: {
      path: {
        org: string;
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Team"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of orgs */
  "get_api-v1-orgs-4bb4bb74212e29d1e33641b38d211873": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add an org */
  "post_api-v1-org-4d6e7ea32cc332b1579e5eb57812ec6c": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewOrg"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Org"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get one event by ID */
  "get_api-v1-event-616b52a3214d1d1a472d3a61bef77f20": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update event */
  "put_api-v1-event-616b52a3214d1d1a472d3a61bef77f20": {
    parameters: {
      path: {
        event: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Event"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of groups */
  "get_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add a group */
  "post_api-v1-event-6e29cbdb5e0ae2f26ebeb4172e8bf7d5": {
    parameters: {
      path: {
        event: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewGroup"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update group */
  "put_api-v1-group-44e4a130606b544f6ab5a1532e35bc29": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** delete a group */
  "delete_api-v1-group-0b9bee095d760068add3c5fe8a467e8b": {
    parameters: {
      path: {
        group: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get org list for a given event */
  "get_api-v1-event-45c1132012c55c1196f21c335b92f888": {
    parameters: {
      path: {
        event: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EventOrg"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** update team */
  "put_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Team"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** create a new team */
  "post_api-v1-team-1d85c5df18ae253cffeaa9339e9ed5cb": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewTeam"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Team"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** set status for event per org */
  "put_api-v1-event-de93f4166d70a3ac4838a8865d319cc1": {
    parameters: {
      path: {
        event: string;
        org: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventOrgStateUpdate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** get list of events */
  "get_api-v1-events-bc4c42038b2c2f0b5c7deb650fb28842": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
  /** add an event */
  "post_api-v1-event-28122581fdbc5bd19bb7de68ab3a43f6": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewEvent"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Forbidden */
      403: {
        content: never;
      };
      /** @description Not Found */
      404: {
        content: never;
      };
      /** @description Invalid input */
      405: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: never;
      };
    };
  };
}
